### ISSUE TITLE
Minimum node version?

### ISSUE THREAD

**Issue by IanVS** [matheuss/hpm#20]
I am running node 5.11.0, but when I try to use `hpm`, I get:

```
> hpm -h
/Users/ianvs/.nvm/versions/node/v5.11.0/lib/node_modules/hpm-cli/index.js:3
const {rename, writeFileSync} = require('fs');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
```

Is there a minimum node version that you support?

**Comment by matheuss** [comment]
Hm, I thought that this shorthand worked on Node 5. Thanks for reporting! Now we require [`node >= 4`](https://github.com/matheuss/hpm/commit/d3cf3b55df410460b98d0cc3747dedda73f3c8ee#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) ☺️

**Comment by matheuss** [comment]
It's out: [`v1.2.3`](https://github.com/matheuss/hpm/releases/tag/v1.2.3)

**Comment by IanVS** [comment]
Wow, that was fast!  Working great now, thanks!
