### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by matheuss** [matheuss/hpm#5]
I found that running tests is a little hard with the code we have. We are [requiring](https://github.com/matheuss/hpm/blob/master/hyperterm.js#L11) `~/.hyperterm.js`. We can't mock the `require` nor `fs` ([mock-fs](https://github.com/tschaub/mock-fs), [mock-require](https://github.com/boblauer/mock-require)). 

My first approach was to backup `~/.hyperterm.js` in a [`before` hook](https://github.com/avajs/ava#before--after-hooks). That works, but creates a problem: HyperTerm goes crazy with all te changes being made to its config file (see zeit/hyperterm#281).

I'm open to ideas on that 😊

PS: I'm waiting on this to release `v1.0.0` 😩

**Comment by nfcampos** [comment]
but you can patch `require`, eg.
```js
// test/setup.js
const Module = require('module')

let CONFIG = {}

module.exports = {
  patch: function() {
    Module.prototype.require = function patchedRequire(_require) {
      const isDotHypertermDotJs = /\.hyperterm\.js$/
      return function(name, ...args) {
        if (isDotHypertermDotJs.test(name))
          return 

        return _require.call(this, name, ...args)
      }
    }(Module.prototype.require)
  },

  get: function() {
    return Object.assign({}, CONFIG)
  },

  reset: function() {
    CONFIG = {}
  },
}
```

```js
// test/test-install.js

const {patch, get, reset} = require('./setup')
const hpm = require('../')

describe('install', function() {
  it('actually installs', function() {
    hpm.install('blah')
    get().plugins[0] === 'blah'
  })
})
```
something like this?

**Comment by matheuss** [comment]
Wow, good idea. I'll try this later today 😊

**Comment by nfcampos** [comment]
@matheuss actually now looking at your code more attentively it looks like you need to do something similar to `fs.writeFile` which is what you use to write to the file, but it shouldn't be too different

**Comment by nfcampos** [comment]
in which case you can just use https://github.com/tschaub/mock-fs no?

**Comment by matheuss** [comment]
Yes, for that part `mock-fs` is enough :) My problem is with the `require` – that can't be mocked in that case. But if I understood you code, it will be enough :)

**Comment by nfcampos** [comment]
ah yes, for that part, yep should work i think
btw, don't you need to refresh the required config file after you install a plugin https://github.com/matheuss/hpm/blob/master/hyperterm.js#L39 so that a call to `isInstalled` afterwards reflects the new installed plugin?
or is it unnecessary because this will always run as a cli tool, so the process dies right after the install is done?

**Comment by matheuss** [comment]
> or is it unnecessary because this will always run as a cli tool, so the process dies right after the install is done?
Exactly. `contents` will never be outdated :)

**Comment by matheuss** [comment]
Done! @nfcampos thanks for the help! When implementing what you suggested, I noticed that we can, indeed, use `mock-fs` and `mock-require`! In fact, the code that you wrote follows the same idea of `mock-require` 😊 Thanks again!
