### ISSUE TITLE
Support Common Uninstall Aliases

### ISSUE THREAD

**Issue by tjfwalker** [matheuss/hpm#6]
Alias `rm`, `remove`, et cetera to `uninstall`.

```
❯ hpm rm <plugin>

❯ hpm remove <plugin>
```

**Comment by tjfwalker** [comment]
Example: [npm uninstall docs](https://docs.npmjs.com/cli/uninstall)
<img width="747" alt="screen shot 2016-07-19 at 11 15 10" src="https://cloud.githubusercontent.com/assets/2547625/16961398/2eb27234-4da2-11e6-90a0-5f28ad3cb3a5.png">

**Comment by matheuss** [comment]
Good idea, especially because we offer `ls` 😊
